# Generated by Django 4.2 on 2025-04-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='paginas',
            field=models.IntegerField(default=0),
        ),
    ]
